### ISSUE TITLE
Invalid hook 'frontpage' for module 'saml2debug'

### ISSUE THREAD

**Issue by regis92** [simplesamlphp/simplesamlphp-module-saml2debug#2]
Hi, I get this error :

![image](https://user-images.githubusercontent.com/36135754/119685481-af6b5580-be45-11eb-879a-7d20469e1815.png)

... Issue or incorrect installation ?

**Comment by tvdijen** [comment]
Looks like a bug.. I'll try and investigate tonight

**Comment by tvdijen** [comment]
v1.0.2 solves this issue!
