### ISSUE TITLE
Module non-functional with missing links and broken URLs

### ISSUE THREAD

**Issue by juanpalaciosascend** [simplesamlphp/simplesamlphp-module-saml2debug#4]
The 'dev-master' tag of this module's composer package installs a broken installation, with links to it in the Federation tab, as advertised by the documentation, missing, and the only link I can find on the admin module's landing page leading to a broken (404) '/module.php/saml2debug/debug.php' URL.

I'm currently running SimpleSAMLphp 2.0.2, installed via composer, on PHP 8.1 and under PHP-FPM. Please let me know if you need any more information from my deployment to debug the issue.

Thank you!

**Comment by tvdijen** [comment]
Links & routes were fixed in `dev-master`, however, the forms are still broken. Needs work.

**Comment by juanpalaciosascend** [comment]
I just installed a4eb536400d2d0e9b776f3edc19ecacb1d8b96fa via composer, and I do see the changes to the routes.yaml file having made it to vendor/simplesamlphp/simplesamlphp/modules/saml2debug/routing/routes. However, I'm still only seeing the 'SAML 2.0 Debugger' link in the admin panel's landing page leading to the same broken '/module.php/saml2debug/debug.php' URL, and no link in the Federation tab.

**Comment by tvdijen** [comment]
Fixed in v1.0.5

**Comment by juanpalaciosascend** [comment]
Confirmed as working (though still no debug href in the Federation tab, so I guess the documentation is incorrect in that regard). Thank you!

**Comment by tvdijen** [comment]
![afbeelding](https://user-images.githubusercontent.com/841045/228671866-f2abc2e7-3902-4a99-8346-c50fdab7abca.png)
You don't see this link?

**Comment by tvdijen** [comment]
Ah wait, you say federation tab.. No, that must be a glitch in the docs.. It has always been on the frontpage

**Comment by juanpalaciosascend** [comment]
Yeah, exactly, the README talks about the Federation tab, but what I see that exact link you asked about in your previous comment in the admin panel's landing page.

**Comment by tvdijen** [comment]
I just fixed the README to point users to the Configuration-tab. Thanks for reporting!

**Comment by juanpalaciosascend** [comment]
Np! Thanks for the quick and awesome work!
